image: oven/bun:latest

stages:
  - build

build:
  stage: build
  script:
    - cd status
    - bun i
    - bun run build
  artifacts:
    paths:
      - dist/go/
      - dist/ts/
      - dist/dart/
#stages:
#  - mirror
#
#mirror_to_repo1:
#  stage: mirror
#  script:
#    - git remote add mirror1 https://gitlab.com/standart-dev/share-go.git
#    - git add status/dist/status/status.go
#    - git push --mirror mirror1
#  only:
#    - main  # Укажите ветку или условие
#
#mirror_to_repo2:
#  stage: mirror
#  script:
#    - git remote add mirror2 https://gitlab.com/standart-dev/share-ts.git
#    - git push --mirror mirror2
#  only:
#    - main  # Укажите другую ветку или условие