stages:
  - build
  - deploy

build:
  stage: build
  image: oven/bun:canary-debian
  script:
    - cd status
    - bun i
    - bun run build
    - ls -R dist/
  artifacts:
    paths:
      - status/dist/go/
      - status/dist/ts/
      - status/dist/dart/

deploy_go:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git remote add mirror1 https://pa-khan:Didaandpes9!@gitlab.com/standart-dev/share-go.git
    - git add -f status/dist/go/
    - git push --mirror mirror1
  only:
    - main
  dependencies:
    - build
#stages:
#  - mirror
#
#mirror_to_repo1:
#  stage: mirror
#  script:
#    - git remote add mirror1 https://gitlab.com/standart-dev/share-go.git
#    - git add status/dist/status/status.go
#    - git push --mirror mirror1
#  only:
#    - main  # Укажите ветку или условие
#
#mirror_to_repo2:
#  stage: mirror
#  script:
#    - git remote add mirror2 https://gitlab.com/standart-dev/share-ts.git
#    - git push --mirror mirror2
#  only:
#    - main  # Укажите другую ветку или условие