enum: Status
output:
  go: ./dist/go/status/status.go
  ts: ./dist/ts/status/status.ts
  dart: ./dist/dart/status/status.dart

list:
  Success: Успешно
  Any: Любая ошибка
  NotFound: Не найдено
  PermissionDenied: Недостаточно прав
  TooFrequentRequests: Слишком частые запросы
  InternalError: Внутренняя ошибка сервера
  ManyConnections: Много подключений
  NotEnoughArguments: Недостаточно аргументов
  NotAuthorized: Не авторизован
  Authorized: Уже авторизован
  IncorrectValue: Неверное значение
  Inactivity: Бездействие
  Timeout: Время ожидания истекло
  InvalidInput: Неверный ввод
  ResourceUnavailable: Ресурс недоступен
  OperationFailed: Операция не удалась